/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_king_jnidemo_MyJni */

#ifndef _Included_com_github_king_jnidemo_MyJni
#define _Included_com_github_king_jnidemo_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_king_jnidemo_MyJni
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_king_jnidemo_MyJni_stringFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
